### ISSUE TITLE
Repository 'https://github.com/njelly/TofuBootstrap.git/' not found

### ISSUE THREAD

**Issue by Jlabarca** [njelly/TofuECS_Rogue#1]
https://github.com/njelly/TofuECS_Rogue/blob/cd6b8e6aa58c69732d4da2ab1d8c2225fa217530/Packages/manifest.json#L3

**Comment by njelly** [comment]
I suppose that would be useful, wouldn't it? I'll go ahead and make that public.

**Comment by njelly** [comment]
This should be fixed. However, I'll point out that the TofuBootstrap repo is not related at all to the TofuECS framework. It's just some personal scripts I've used over the years. I wouldn't really recommend anyone actually "play" this game yet. There's not even any floor generation! The important things are in the ECS related code (the `Tofunaut.TofuECS_Rogue.ECS` and `Tofunaut.TofuECS_Rogue.ECSUnity` namespaces)

I really appreciate your interest in the project. Please don't hesitate to ask questions, contribute, or request features. :)
